Add docker files for support
Rethunk-Tech/nextjs-boilerplate pull request #47
Opened 2022-06-16 12:16 UTC by gissf1

2022-06-16 18:45 UTC, AlbinoGeek requested changes
Please consider the reviewed changes and push an updated commit.

Thank you for your contributions!

2022-06-16 18:45 UTC, AlbinoGeek commented on .yarnrc.yml
> +globalFolder: "/cache/yarn"
This shouldn't be set on the host. Perhaps add something like the following to the Dockerfile to make sure it's only used within CI:

```bash
echo 'globalFolder: "/cache/yarn"' >> .yarnrc.yml
```

2022-06-16 18:45 UTC, AlbinoGeek commented on docker-compose.yml
> +      - 80:8080
Only port `9000` (container) is necessary. You could either forward `9000` (container) to `80` (host), or remove this (extra) ports entry.

2022-06-16 18:45 UTC, AlbinoGeek commented on docker-compose.yml
> +      - 80:8080
Only port `9000` (container) is necessary. You could either forward `9000` (container) to `80` (host), or remove this (extra) ports entry.

2022-06-16 18:45 UTC, AlbinoGeek commented on docker-compose.yml
> +services:
I may be wrong, but doesn't specifying multiple services within one `docker-compose.yml` cause them all to be created? It wouldn't make sense to launch both the dev and prod versions of an application in the same composition, I don't think.

Basically, keep the definition for `nextjs` in this file, then move the `nextjs-dev` service to a new file called `docker-compose.dev.yml`.

For more information, see: https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

2022-06-16 18:45 UTC, AlbinoGeek commented on Dockerfile
> +CMD yarn dlx next start
CMD should be: `yarn run dev`

This will use the `dev` command configured in `packages.json`.

2022-06-16 18:45 UTC, AlbinoGeek commented on Dockerfile
> +CMD yarn dlx next start
So, for a PRODUCTION build, you need to:

1) `yarn run build` to create `.next/...`
2) `yarn run export` to create `out/...` from `.next/...`
3) CMD should be an alpine HTTP server hosting `out/`

(This can be done in its own build stage, which will save over a gigabyte in the end-result, as the production image should only contain alpine HTTPd, and the generated `out/` HTML files.)

2022-06-16 20:17 UTC, gissf1 commented on docker-compose.yml
> +      - 80:8080
Yeah, I wasn't sure what I wanted to do here.  I removed the port 80 map, as you suggested.  This change will be in the next push.

2022-06-16 20:17 UTC, gissf1 commented on docker-compose.yml
> +      - 80:8080
I wasn't sure what I wanted to do here.  I removed the port 80 map, as you suggested.  This change will be in the next push.

2022-06-16 23:52 UTC, gissf1 commented on docker-compose.yml
> +services:
Correct.  And I hadn't run it yet, as I was only doing builds, so I didn't run across it.  I'm actually going to restructure a few things, but I wouldn't recommend doing the `.dev` suffix for docker-compose.  More commonly, docker-compose uses configuration variables to specify things like that.

2022-06-17 00:02 UTC, gissf1 commented on .yarnrc.yml
> +globalFolder: "/cache/yarn"
Why wouldn't we want to reuse the module cache when building?  If anything, I'd say we can remove the global cache stuff after building.  Let me work on this refactor and commit, then we can review the results of the next revision and determine the path forward from there.

2022-06-17 00:34 UTC, gissf1 commented on Dockerfile
> +CMD yarn dlx next start
Done.  Will be in the next update.

2022-06-17 07:33 UTC, gissf1 commented on docker-compose.yml
> +services:
Fixed in the in the next push.

2022-06-17 07:34 UTC, gissf1 commented on Dockerfile
> +CMD yarn dlx next start
Fixed in the next push.  Thanks for the excellent helpful instructions!

2022-06-17 07:35 UTC, gissf1 commented on .yarnrc.yml
> +globalFolder: "/cache/yarn"
Ah, that makes sense.  I'll likely have to fix this closer to your suggestion, but that will be in round 3.

2022-06-17 07:53 UTC, gissf1 commented on .yarnrc.yml
> +globalFolder: "/cache/yarn"
Yup, now this issue is causing the PR to fail CI builds, so my next step is clear.

2022-06-17 08:57 UTC, gissf1 commented on .yarnrc.yml
> +globalFolder: "/cache/yarn"
This has been fixed in the latest push.

2022-06-17 21:56 UTC, AlbinoGeek approved these changes
Looks good to me.

There are some things that can be optimized, but that's for later.

2022-06-17 21:56 UTC, AlbinoGeek commented on Dockerfile
> +COPY --from=nextjs-builder [ "$HOME/out", "$HOME/" ]
You should only need `$HOME/out`, which should reduce the output quite a bit.

2022-06-17 21:56 UTC, merged